grafana:
  enabled: true
alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: {}
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
server:
  extraArgs:
    storage.tsdb.retention: 24h
serverFiles:
  alerts: {}
  prometheus.yml: {}
  rules: {}

prometheusOperator:
  createCustomResource: false
prometheus:
  prometheusSpec:
    thanos:
      baseImage: thanosio/thanos
      version: v0.8.1
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
