grafana:
  enabled: true
alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: {}
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
server:
  extraArgs:
    storage.tsdb.retention: 24h

serverFiles:
  alerts: {}
  prometheus.yml: {}
  rules: {}

prometheusOperator:
  createCustomResource: false

prometheus:
  prometheusSpec:
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          resources:
            requests:
              storage: 1Gi
    thanos:
      baseImage: thanosio/thanos
      version: v0.13.0
      listenLocal: true
      logLevel: debug
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
