apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-kube-state-metrics
spec:
  containers:
    - name: kube-state-metrics
      resources:
        limits:
          cpu: 25m
          memory: 250Mi
        requests:
          cpu: 25m
          memory: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-prometheus-oper-operator
spec:
  template:
    spec:
      containers:
        - name: prometheus-operator
          resources:
            limits:
              cpu: 12m
              memory: 125Mi
            requests:
              cpu: 12m
              memory: 125Mi
        - name: tls-proxy
          resources:
            limits:
              cpu: 12m
              memory: 125Mi
            requests:
              cpu: 12m
              memory: 125Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:     
  name: monitoring-kube-state-metrics
spec:
  template:
    spec:
      containers:
        - name: kube-state-metrics
          resources:
            limits:
              cpu: 25m
              memory: 250Mi
            requests:
              cpu: 25m
              memory: 250Mi
