apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patches:
  - target:
      kind: Deployment
      name: monitoring-kube-state-metrics
    path: kube-state.yaml
  - target:
      kind: Deployment
      name: monitoring-prometheus-oper-operator
    path: prom-op.yaml
