---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"

spec:
  alertmanager:
    enabled: false
  alertmanagerFiles:
    alertmanager.yml: ""
  nodeExporter:
    enabled: true
  pushgateway:
    enabled: false
  server:
    extraArgs:
      storage.local.retention: 24h
  serverFiles:
    alerts: ""
    prometheus.yml: ""
    rules: "" 
