alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: {}
nodeExporter:
  enabled: true
pushgateway:
  enabled: false
server:
  extraArgs:
    storage.local.retention: 24h
serverFiles:
  alerts: {}
  prometheus.yml: {}
  rules: {}
